import org.openqa.selenium.Alert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.ArrayList;
import java.util.Random;

/** TEST 4.5: User is sending Fuzzed input.*/
public class Test4_5 {
    public static void main(String[] args) throws InterruptedException {
        FirefoxDriver driver = new FirefoxDriver();
        // Enter the URL generated by ngrok
        driver.get("http://a4fc5abf.ngrok.io");


        /** Code for Simple Fuzzer */

        Random random = new Random();

        // strings of any length between 0 and 1024
        double length = random.nextInt(1024);
        int string_length = (int) length;
        System.out.println("input length = " + string_length);
        String[] input = new String[string_length];

        //generate a random character at each location of the string
        for (int index = 0; index < string_length; index++) {
            double between_0_and_1 = random.nextDouble();
            //generate a character between ASCII 32 and 128
            double AsciiNumber = between_0_and_1 * 96 + 32;
            input[index] = (Character.toString((char)(AsciiNumber)));
            System.out.println(input[index]);
        }

        // here is the input string to fuzz
        System.out.println("" + input.toString());
        /***/



        /** Test 1*/
        WebElement three = driver.findElement(By.id("password"));
        // Check if Issue 3 is found by Selenium
        System.out.println("Password is Selected.");

        Thread.sleep(5000);

        // Select Issue 3
        three.click();

        Thread.sleep(2000);

        /***/

        /** Test 2*/
        WebElement chat = driver.findElement(By.id("Chat"));
        // Check if chat is found by Selenium
        System.out.println("Chat is Selected.");

        //Thread.sleep(2000);

        // Select Issue 3
        chat.click();

        Thread.sleep(2000);

        /***/

        /** Test 3*/
        WebElement next = driver.findElement(By.id("Next"));
        next.click();

        Thread.sleep(5000);

        // Dismiss the alert.
        driver.switchTo().alert().accept();

        // Wait for the page to be redirected.
        WebDriverWait wait = new WebDriverWait(driver, 20);
        wait.until(ExpectedConditions.elementToBeClickable(By.id("endButton")));

        Thread.sleep(5000);

        /***/

        WebElement textarea = driver.findElement(By.id("sendBox"));
        textarea.sendKeys(input);
        Thread.sleep(2000);
        WebElement send = driver.findElement(By.id("sendButton"));
        send.click();

        Thread.sleep(3000);

        driver.switchTo().alert().accept();
        Thread.sleep(2000);
        WebElement end = driver.findElement(By.id("endButton"));
        end.click();
        Thread.sleep(2000);
        Alert alert = driver.switchTo().alert();
        alert.accept(); // for OK
        Thread.sleep(3000);
        // Close the browser
        driver.close();

    }
}